---
title: "Post–Surgery Resting Energy Expenditure"
author: "Eunice Lee"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: false
editor: visual
---

# Background & Motivation

Resting energy expenditure (REE) represents the metabolic energy required to sustain essential physiological function, and plays a critical role in guiding nutritional support for patients after surgery. Prior research suggests that obesity, ventilator dependence, and illness severity may influence both the baseline level and trajectory of metabolic demand, yet the characterization of these effects in clinical populations remains incomplete. To address this need for a comprehensive evaluation, 11 post-operative patients were assessed with follow-up measurements taken longitudinally at different stages of recovery. Our objective is to develop an appropriate modeling framework that investigates how raw and weight-adjusted REE change over time, and to determine how these patterns differ based on clinical factors including obesity status, ventilator use, and patient location (ICU vs SDU).

# Data & Exploratory Analysis

Our data includes 35 indirect calorimetry measurements collected from 11 post-operative cardiac surgery patients (4 obese, 7 non-obese), each contibuting between 1 to 5 observations over recovery. Key variables include absolute REE, weight-adjusted REE (per kg), obesity status, ventilator use, location (ICU or SDU), and measurement index representing follow-up time ordinally.

To explore this data, the overall distributions of REE and REE/kg were first examined. Despite a slight right-skew, values were overall continuous and suitable for linear modeling. (Figure 1A-B) Cross-sectional comparisons by location and ventilator use further revealed elevated metabolic requirements in ICU over SDU, and ventilated over non-ventilated patients. (Figure 2A-B, 3A-B) Here, it was important to note that ventilators were only used in the ICU, informing us that its effect should only be considered for measurements taken in the ICU to prevent any misleading interpretations in SDU. (Figure 4) Furthermore, scatterplots of REE and REE/kg over time displayed non-parallel trends across obesity groups, indicating that obese patients tend to have higher absolute REE but smaller differences in REE/kg, suggesting different effects of obesity on metabolic demand when adjusted for body weight. (Figure 5A-B) The same pattern could be observed through boxplots grouped by obesity groups as well. (Figure 6A-B) Altogether, this suggested that all factors had potential correlation to REE, and that measurement (time) was possibly associated with obesity status and location (ICU/SDU) as an interaction effect.

Guided by this exploratory data analysis, we initially tried fitting a linear mixed-effects models containing all variables in addition to two potential interaction effects: (1) obesity and measurement (2) location and measurement. Results showed that including the obesity-measurement interaction term substantially improved model fit, supporting the hypothesis that metablic recovery differs between obese and non-obese patients. However, adding the location-measurement interaction term did not improve fit based on AIC/BIC caluclations, and yielded non-significant effects for both REE and REE/kg. (Figure 7) As this indicated that rate of change over time is likely not associated with ICU versus SDU patients, the location-measurement interaction was dropped in the final model to avoid multicollinearity.

# Model Rationale, Implementation, Evaluation

## Model Rationale
As each patient contributed multiple REE measurements at different time points in recovery, a linear mixed-effects model was implemented to properly account for correlation among repeated measurements from the same patient. This framework allows us to separately account for between-patient diferences in baseline metabolic level and within-patient changes over time. As our exploratory analysis suggested that obesity may affect how REE changes across recovery, whiile ICU location mainly affects baseline REE rather than its slope, we included an obesity-measurement interaction in the final model, with ventilator use and location as additional fixed effects. Hence, for \(i = 1, \dots, 11\) patients and \(j = 1, \dots, n_i\) repeated REE observations per patient, our final model was:

Absolute REE:
$$
\begin{aligned}
\text{REE}_{ij} 
    &= \beta_0 
     + \beta_1 \text{Obesity}_i
     + \beta_2 \text{Measurement}_{ij} \\
    &\quad + \beta_3 (\text{Obesity}_i \times \text{Measurement}_{ij})
     + \beta_4 \text{Location}_{ij} \\
    &\quad + \beta_5 \text{Ventilator}_{ij}
     + \mu_i + \varepsilon_{ij}
\end{aligned}
$$
Weight-adjusted REE:
$$
\begin{aligned}
\text{REEperKG}_{ij} 
    &= \beta_0 
     + \beta_1 \text{Obesity}_i
     + \beta_2 \text{Measurement}_{ij} \\
    &\quad + \beta_3 (\text{Obesity}_i \times \text{Measurement}_{ij})
     + \beta_4 \text{Location}_{ij} \\
    &\quad + \beta_5 \text{Ventilator}_{ij}
     + \mu_i + \varepsilon_{ij}
\end{aligned}
$$

For both cases, random effects and residual errors were modeled as:
$$
\mu_i \sim \mathcal{N}(0, \sigma_\mu^2), \quad
\varepsilon_{ij} \sim \mathcal{N}(0, \sigma^2)
$$
The random intercept $\mu_i$ captures between-patient variation in baseline REE, reflecting the substantial differences that were observed in our EDA. (Figure 8) The residual error $\varepsilon_{ij}$ represents within-patient variation not explained by the fixed effects. A random slope was initially considered for measurement, but was excluded since most patients only had 1-3 repeated observations, leading to insufficient amount of data for a reliable slop estimation. (Figure 9)

## Model Implementation
We implemented this model using the lme4 package in R. This decision to use a frequentist LMM model rather than a Bayesian framework was due to several reasons. First, given our very small sample size, making fully Bayesian hierarchical estimation would be less stable in the absence of informative priors. As the primary goal of this study is to make inferences on fixed effects rather than full posterior uncertainty quantification, and exploratory analysis showed that assumptions of linearity and normality could be justified, the frequentist approach was much more simple and suitable for this analysis.

## Model Evaluation
To assess model fit for both REE and REE/kg, we plotted residual vs fitted values and observed no strong evidence of heteroscedasticity. With residuals generally centered around zero across the fitted values and randomly scattered, the constant variance assumption was met since no clear clustering or fanning patterns were present. (Figure 10A-B) The Q-Q plots for both residuals and random effects demonstrated approximate normality, with minor deviations in the tails but no substantial departures from our model assumptions. (Figure 11A-B, 12A-B). To check for linearity of observations over time, residuals were also plotted against the measurement index. As no strong patterns were found beyond slight curvature, our use of measurement as a linear fixed effect was therefore supported. (Figure 13A-B).

# Results
Our model estimated a baseline intercept of 1497.43kcal/day for expected REE at the first post-operative measurement for a non-obese, non-ventilated ICU patient. Obesity had a large positive baseline effect ($\beta_1=920.25; p=0.0019$), indicating that obese patients began recovery with a significantly higher initial REE than non-obese patients. However, the negative obesity-measurement interaction ($\beta_3=-205.42; p=0.05$) demonstrated that obese patients experience a greater decline over time, whereas non-obese patients’ REE remain relatively stable or even slightly increase. Location did not have a significant effect on metabolic recovery with a p-value of 0.14, while ventilator use exhibited a modestly negative association with REE ($\beta_5=-289.40; p=0.081$) for patients in ICU. This agreed with our hypothesis since ventilated patients would have reduced work of breathing, and no observations in SDU used ventilators as discussed. Observing our random effects, substantial between-patient variability was observed with a random intercept standard deviation of 187.7kcal/day. This was consistent with our observation of large variance in baseline metabolic demands by patient, supporting the need for a mixed- effects model. The residual standard deviation of 280.3kcal/day reflected within-patient variance across measurements at different time points, demonstrating the expected physiological variability and noise in the indirect calorimetry device itself. (Table 1)

To assess if our results changed when adjusted for body weight, the same model was applied to REE/kg as the response variable. Notably, this removed the large baseline difference between obese and non-obese patients, as the effect of obesity as no longer significant ($p=0.32$) with a gentle slope of 4.12. This indicated that a significant part of difference in absolute REE is in fact explained by body mass. However, the obesity-measurement interaction remained significant and negative ($\beta_3=-3.45; p=0.01$), implying that differences in recovery slope remain significant even after normalization by weight. Fixed effects of location and ventilator use mirrored the same direction in slope but were smaller in magnitude, suggesting reduced variability in the weight-adjusted outcomes. (Table 2)

# Conclusion & Future Work
In conclusion, this study examined how resting energy expenditure changes during post-operative recovery in 11 cardiac surgery patients and how trends differ by their obesity status, ventilator use, and location. Our findings reveal that obesity status affects both the baseline level and longitudinal trajectory of REE, as obese patients begin recovery with substantially higher metabolic demand but exhibits steeper decline over time compared to non-obese patients. Patients in ICU have higher baseline REE than in SDU, clinically consistent with greater physiological stress in the intensive unit, but their recovery slopes do not differ significantly by location. Among ICU patients, ventilator use was associated with modest levels of reduction in REE as expected, given the reduced work of breathing. When REE was adjusted for body weight, baseline differences between obese and non-obese patients were no longer present. However, differences in recovery rates persisted, showing that obesity still influences longitudinal trends of metabolic recovery.

Our study included some limitations, the main one being that measurement times were considered as an ordinal variable despite varying time intervals between each index. This assumes evenly spaced recovery time that may not accurately reflect the true timing. While our residual plot by measurement suggested that the linearity assumption was reasonably satisfied, future work should collect the precise intervals to treat time as a continuous variable. Moreover, the small sample size, unbalanced number of repeated measurements per patient, and absence of ventilator use data for patients in SDU were major limitations in availability of our data. While our model diagnostics supported a decently good fit through a mixed-effects framework, future work could be done with richer data to better predict individual recovery patterns in a more refined manner.

\pagebreak

# Appendix